library(rmarkdown)
render("concatenateDepthMeasurements.R",output_format="html_document", knit_root_dir = "../")
render("exploratoryDataAnalysis.R",output_format="html_document", knit_root_dir = "../")
render("createPredictorStack.R",output_format="html_document", knit_root_dir = "../")
render("createDataFrame.R",output_format="html_document", knit_root_dir = "../")
render("modelDepth.R", output_format="html_document", knit_root_dir = "../")
render("evaluateDMK.R",output_format="html_document", knit_root_dir = "../")